// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU8ouXB9Pmj0GENCfF1xC6VJwOKlb662o',
    appId: '1:82660505493:web:2b58792e7854b07498689c',
    messagingSenderId: '82660505493',
    projectId: 'auth-bd27f',
    authDomain: 'auth-bd27f.firebaseapp.com',
    storageBucket: 'auth-bd27f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAa13rFFqpTOLBNETuNLHVbhIpK0G0-vU',
    appId: '1:82660505493:android:50408ac84558e04698689c',
    messagingSenderId: '82660505493',
    projectId: 'auth-bd27f',
    storageBucket: 'auth-bd27f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG5KHY_rIMT27Ww-aGgOhTYRjpkMmCX9Y',
    appId: '1:82660505493:ios:fb0d9154a5b9148298689c',
    messagingSenderId: '82660505493',
    projectId: 'auth-bd27f',
    storageBucket: 'auth-bd27f.appspot.com',
    iosBundleId: 'com.example.vote2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBG5KHY_rIMT27Ww-aGgOhTYRjpkMmCX9Y',
    appId: '1:82660505493:ios:fb0d9154a5b9148298689c',
    messagingSenderId: '82660505493',
    projectId: 'auth-bd27f',
    storageBucket: 'auth-bd27f.appspot.com',
    iosBundleId: 'com.example.vote2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU8ouXB9Pmj0GENCfF1xC6VJwOKlb662o',
    appId: '1:82660505493:web:f7f54f4b492935ed98689c',
    messagingSenderId: '82660505493',
    projectId: 'auth-bd27f',
    authDomain: 'auth-bd27f.firebaseapp.com',
    storageBucket: 'auth-bd27f.appspot.com',
  );
}
